"use client";

import { useMemo } from '@/lib/contexts/memo-context';
import { MemoSection } from './MemoSection';

export function MemoEditor() {
    const { memo, isGenerating } = useMemo();

    if (!memo) {
        return null;
    }

    // Sort sections by their template order
    const sortedSections = [...memo.sections].sort((a, b) => {
        const orderA = memo.template.sections.find(ts => ts.type === a.type)?.order || 999;
        const orderB = memo.template.sections.find(ts => ts.type === b.type)?.order || 999;
        return orderA - orderB;
    });

    return (
        <div className="max-w-4xl mx-auto pb-20">
            {/* Memo Title */}
            <div className="mb-12">
                <h1 className="text-4xl font-bold text-slate-900 mb-2">
                    {memo.title}
                </h1>
                <div className="flex items-center gap-4 text-sm text-slate-600">
                    <span>Created {new Date(memo.createdAt).toLocaleDateString()}</span>
                    <span>•</span>
                    <span>Last updated {new Date(memo.updatedAt).toLocaleDateString()}</span>
                    <span>•</span>
                    <span className="capitalize">{memo.status}</span>
                </div>
            </div>

            {/* Generating overlay */}
            {isGenerating && (
                <div className="mb-6 p-4 bg-indigo-500/10 border border-indigo-500/20 rounded-lg">
                    <div className="flex items-center gap-3">
                        <div className="w-5 h-5 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
                        <p className="text-sm font-medium text-indigo-600">
                            AI is working on your request...
                        </p>
                    </div>
                </div>
            )}

            {/* All Sections */}
            <div className="space-y-8">
                {sortedSections.map((section, index) => (
                    <MemoSection
                        key={section.id}
                        section={section}
                        sectionNumber={index + 1}
                    />
                ))}
            </div>

            {/* Footer */}
            <div className="mt-16 pt-8 border-t border-slate-200">
                <p className="text-sm text-slate-500 text-center">
                    Generated by AI Associate • {memo.metadata.wordCount} words • Version {memo.currentVersion}
                </p>
            </div>
        </div>
    );
}
